# Usage:
# cargo run -- chaos --config chaosfilter.toml

# Name of chaos plan
name = "netem-test"

[targets]
iface = "eth0"
cgroup = "77500" # Optional

[schedule]
duration_s = 10

# qdisc injector
[injectors.network_config]
enabled = true
target_iface = "enp5s0"
delay_ms = 100
loss_percent = 50.0

[injectors.memory_config]
enabled = false
target_pid = 1234
move_pid = true
enable = ["cpu", "memory"]
cpu_max = "20000 100000"
mem_max = "1G"