# This config is based on the one made by the init command and is for the demo.
# No comments or anything just arguments

name = "example-plan"

[targets]
iface = "default"
cgroup = "0"

[schedule]
duration_s = 10

[injectors.network_config]
enabled = true
target_iface = "default"
delay_ms = 400
loss_percent = 50.0

[injectors.memory_config]
enabled = false
target_pid = 0
move_pid = true
enable = ["cpu", "memory"]
cpu_max = "max 100000"
cpu_weight = 100
mem_max = "max"
mem_high = "max"
swap_max = "max"

[injectors.block_config]
enabled = false
device = "/dev/sda"
rbps = 10485760
wbps = 10485760
