[[target]]
name = "chaosfilter help"
kernel = "chaosfilter/tests/kernels/bzImage-v6.2-default"
command = '''/bin/bash -lc '
    ip link set eth0 up
    ip -o link

    cd /mnt/vmtest &&
    cargo build &&
    ./target/debug/chaosfilter validate --config chaosfilter.toml &&

    sleep 10 '
'''

[target.vm]
extra_args = ["-nic", "user,model=virtio-net-pci"]