[package]
name = "aya-qdisc-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
aya-qdisc-common = { path = "../aya-qdisc-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "aya-qdisc"
path = "src/main.rs"
