[package]
name = "chaosfilter-controller"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[features]
cli = ["dep:clap"]

[dependencies]
anyhow = { workspace = true }
aya = { workspace = true }
ctrlc = { workspace = true }
clap = { workspace = true, optional = true}
chaosfilter-common = { path = "../chaosfilter-common" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11+spec-1.1.0"