# Run the config with:
# cargo run -- chaos --config ./chaosfilter/src/test_config.toml
# if you are in the root directory.



# Your test run must have a name.
name = "test-plan"

# I do not like this.  It will change.
# See below in [injectors.memory_config] for memory_config's pid selection.
# iface needs to be moved into injectors.network_config.
[targets]
iface = "enp34s0"
cgroup = "6687"
# Good, and we could add sequencing here for multiple config runs.
[schedule]
duration_s = 120

# This is the injector for qdiscs.rs
[injectors.network_config]
enabled = false
delay_ms = 100
loss_percent = 50.0

# This is the pid_cgroup.rs section.
# Best tested with the following:
#
#sleep 600 &
#echo &!
#
#This will return your PID for testing.

[injectors.memory_config]
enabled = false
pid = 6687
move_pid = true
enable = ["cpu", "memory"]
cpu_max = "20000 100000"
mem_max = "1G"

[injectors.fd_config]
enabled = true
soft_limit = 64
hard_limit = 64
