[package]
name = "chaosfilter-ebpf"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
chaosfilter-common = { path = "../chaosfilter-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[lib]
name = "chaosfilter"
path = "src/lib.rs"
